### ISSUE TITLE
Error with importing PMX, PMD

### ISSUE THREAD

**Issue by MartinSzr** [GRGSIBERIA/mmd-transporter#5]
Dear Eiichi,

first and foremost thank you so much for your work! 

I have problems with the import of pmx as well. I installed everything and manually load the plugin. When I start .loadmmd() I get these errors:

win 7 46 bit
python 2.7.2 32 bit
UAC deactivated
tinywall firewall deactivated

Maya 2014, branch master:
```
maya.cmds.loadmmd()
# Error: RuntimeError: file <string> line 2: WindowsError: file C:\Program Files\Autodesk\Maya2014\bin\python27.zip\subprocess.py line 896: 2 # 
```

Maya 2014, branch cpp-plugin:
```
maya.cmds.loadmmd()
D:/2015_08_HATSUNE MIKU/40_MODELS/01 Mamama's Miku Hatsune Appearance/dl/Appearance Miku.pmx
# Error: RuntimeError: file <string> line 2: UnicodeEncodeError: file C:\Program Files\Autodesk\Maya2014\bin\python27.zip\encodings\cp1252.py line 12: charmap # 
```

Maya 2016, branch master:
```
maya.cmds.loadmmd()

# Error: RuntimeError: file <string> line 2: WindowsError: file C:\Program Files\Autodesk\Maya2016\bin\python27.zip\subprocess.py line 957: 2 # 
```
the line is 957 in 2016, in 2014 it's line 896

Maya 2016, branch cpp-plugin:
```
maya.cmds.loadmmd()
D:/2015_08_HATSUNE MIKU/40_MODELS/01 Mamama's Miku Hatsune Appearance/dl/Appearance Miku.pmx
# Error: RuntimeError: file <string> line 2: UnicodeEncodeError: file C:\Program Files\Autodesk\Maya2016\bin\python27.zip\encodings\cp1252.py line 12: charmap # 
```

Thanks again!

Best,

Martin

**Comment by MartinSzr** [comment]
I read the installation of mecab again. I didn't found _MeCab.pyd, MeCab.py and libmecab-1.dll in the MeCab folder. Only mecab-0.996.exe 

See screenshot:

![untitled-1](https://cloud.githubusercontent.com/assets/14252591/9837277/457a025e-5a3a-11e5-8ff5-36590aa2af24.jpg)


Thank you for your time.

Best,

Martin

**Comment by GRGSIBERIA** [comment]
Hi, Martin.
I'm so sorry, cpp-plugin is working branch. cpp-plugin has not been able to yet implemented.
Please, use master branch.

So, did you see "Install Failed" when run install.py?
if you see "Succeeded", kakasi folder on C:\.
Please, confirm.

**Comment by MartinSzr** [comment]
Hi Eiichi,

thank you for your answer. I deleled the kakasi folder and reinstalled successful:
```
Completed create makedict.bat.
Completed to copy MMD HumanIK.xml.
Completed to copy kakasi directory.

Installing successful.
Please press any key.
```

Best 
Martin

**Comment by MartinSzr** [comment]
Hi Eiichi,

I found out that my problem was: I made a failure with the Python Path and the system variable. I found it out when I tried to use Python with cmd.exe. 

Now I'm able to import mdd models with your plug in. I have still some issues however. 

I'll write soon more about it.

Best,
Martin

**Comment by MartinSzr** [comment]
It works! It was just my python installation... sorry.

Thanks so much
