### ISSUE TITLE
法線の反転とメッシュの崩壊について

### ISSUE THREAD

**Issue by kaisereagle** [GRGSIBERIA/mmd-transporter#7]
お世話になっていますmmd-transporterを使わせていただきましたがPMXファイルを読み込むと上記問題が発生しております
メッシュがtransform1に分解され頭の法線が反転しておりますがこれはTda式ミクのモデルがわるいのでしょうか？
以下に環境を示させていただきます
windows10 Pro 64bit
MAYA Ver
2014、2015、2016
PmxIO for Mayaで読み込んだPMXファイルは正常に読み込めております
※表示状況をUPさせてもらいます
http://or2.mobi/index.php?mode=image&file=151187.jpg
http://or2.mobi/index.php?mode=image&file=151188.jpg
見た感じMAYAのバージョンによってマテリアルがずれてしまっているのかもしれません

**Comment by GRGSIBERIA** [comment]
カメラのメニューから，[Shading]-[Polygon Transparency Sorting]をオンにすると正常に描画されます．Zソートに失敗しているマテリアルがある場合は，この設定をオンにすると透明なポリゴンが正しく描画されます．

**Comment by kaisereagle** [comment]
お早いお返事ありがとうございました
無事、Tda式は表示されました。2016は対応していないのですね。申し訳ありませんでした・
ありがとうございます。

もう一点お聞きしたいのですが別PMXでの読み込みにてボーンが反映されない場合がございます
通常subete_no_oyaにボーンが作成されると思うのですが各メッシュもグループ化されずメッシュがコピーされる場合があるのですが、もし命名規則、ボーンの付け方に仕様等ありましたらご教授いただけませんでしょうか？
http://or2.mobi/index.php?mode=image&file=151195.jpg
何度も申し訳ありません

**Comment by GRGSIBERIA** [comment]
仕様として，PMX Editorの検証ツールでエラーのないモデルがインポートの対象になります．モデルのエラーを解消した上でエクスポートをすれば，よほど複雑なモデルでない限り，読み込めると思います．

**Comment by kaisereagle** [comment]
ご教授ありがとうございます
一応PMDエディタでのPMXデータの状態検証とプラグインのCheckBasicBoneにて検証しましたところ特に問題なくMMDで動くことを確認しているのですが下記エラーがでているもようです。
# エラー: RuntimeError: file <string> line 2: RuntimeError: file D:/3d/mmd-transporter-master/mmd-transporter-master/lib\importer\expgen.py line 49: オブジェクトまたは値が不足しています
こちら      util.setString(groupName, "expression", panelJpNames[panel])にて読み込む必要があるものがたらないのでしょうか？
何度も申し訳ございません

**Comment by GRGSIBERIA** [comment]
読み込めないモデルの名前を教えて頂けますか？

**Comment by kaisereagle** [comment]
こちらになります
http://fast-uploader.com/file/7046233407316/

**Comment by GRGSIBERIA** [comment]
モデルのボーン名に全角英数字が使われています．
NGなのは，全角英数字と半角カタカナ，特殊記号です．日本語を強制的にローマ字に置き換えているため，ローマ字に置き換えられない特殊な文字列は使用できません．
一応，修正しておきますが，対応するのに時間がかかるため該当箇所を修正して利用してください．

**Comment by kaisereagle** [comment]
ありがとうございました。
ボーンに全角はだめなのですね。
そうなると、かなりの数のMMDモデルはきびいですね。
(材質やらボーンはみんな日本語でつけていると思うので)

こちら英数字で対応します。
この度は素晴らしいプラグインをありがとうございました
対応ありがとうございました

**Comment by kaisereagle** [comment]
あ、日本語対応とか大変そうなので参考までに
yomogiさんが公開しているMAYAのMMDインポーターは日本語ファイルをbase64で一度エンコードしてから名前をつけて読み込んでいるっぽいです
http://mayatech.blog.jp/archives/3009881.html
もし参考になればどうぞ

**Comment by GRGSIBERIA** [comment]
全角文字（ひらがな，カタカナ，漢字）はいいのですが，例外的に全角英数字，全角・半角記号，半角カタカナだけ対応していません．PMXをCSVで書き出して，正規表現で修正するのが現状では最も手早いと思います．

**Comment by kaisereagle** [comment]
わざわざ有り難うございます。
確かにテキストで修正するほうが早いですね
微妙に全角の１～９の文字とか大変ですがｗ
やってみます！

**Comment by GRGSIBERIA** [comment]
masterで修正しました．Maya 2016にも対応しました．頂いたデータについては，Maya上で再現不可能なケースがあるため，エラー文を読んで修正を試みてください．

**Comment by kaisereagle** [comment]
おお！お早い修正ありがとうございます！
確認してみます！

**Comment by kaisereagle** [comment]
ちょっとお聞きしたいのですが新しいリポジトリからダウンロードしてきたのですがmecabフォルダにlibmecab-1.dllと_MeCab.pydがないのですがこちらmecabはなくても動きますでしょうか

**Comment by GRGSIBERIA** [comment]
いくつかリポジトリに反映されていないファイルがあることに気が付きました．後日修正します．

**Comment by GRGSIBERIA** [comment]
遅くなりましたが修正しました．現状のREADMEに書かれていることが正しいです．

**Comment by kaisereagle** [comment]
了解いたしました
見てみます
